accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
	login, 
	logout,
	password_reset,
	password_reset_done,
	password_reset_confirm,
	password_reset_complete
)

app_name = "accounts"


urlpatterns = [
	
	path(r'login/', login, {'template_name': 'accounts/login.html'}, name = 'login'),
	path(r'logout/', logout, {'template_name': 'accounts/logout.html'}, name = 'logout'),
	path(r'register/', views.register, name ='register'),
	path(r'profile/', views.view_profile, name = 'view_profile'),
	path(r'profile/(P<pk>\d+)/', views.view_profile, name='view_profile_with_pk'),
	path(r'profile/edit/', views.edit_profile, name = 'edit_profile' ),
	

	path(r'change-password/', views.change_password, name = 'change_password' ),

	path(r'reset-password/', password_reset, {'template_name':
	'accounts/reset_password.html', 'post_reset_redirect': 
	'accounts:password_reset_done', 'email_template_name': 'accounts/resest_password_email.html'}, name = 'reset_password'),

	path(r'reset-password/done/', password_reset_done,{'template_name': 'accounts/reset_password_done.html'}, name = 'password_reset_done'),

	path(r'reset-password/confirm/(<uidb64>[0-9A-Za-z]+)-(<token>.+)/', password_reset_confirm, 
		{'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),


	path(r'reset-password/complete/', password_reset_complete, {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')

]

posthole/urls.py
from django.contrib import admin
from django.urls import path, include
from posthole import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('', views.login_redirect, name = 'login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace = 'accounts')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	bio = models.CharField(max_length = 255, default = '')
	website = models.URLField(default = '', blank=True)
	nickname = models.CharField(max_length = 50, default = 'user', blank=True)
	#image = models.ImageField(upload_to='profile_image', blank=True)


	def __str__(self):
		return self.user.username

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user = kwargs['instance'])

post_save.connect(create_profile, sender = User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required = True)

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
		)

	def save(self,commit = True):
		user = super(RegistrationForm, self).save(commit = False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']


		if commit:
			user.save()

		return user

class EditProfileForm(UserChangeForm):
	  

	class Meta:
		model = User
		fields = (
			'email',
			'first_name',
			'last_name'
		)

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

posthole/views.py
from django.shortcuts import redirect


def login_redirect(request):
	return redirect('/account/login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}

<title>Change your password</title>

{% endblock %}

	{% block body %}
	<div class="container">
	
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit">Submit</button>
			}
		</form>

	</div>
	
	{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}

<title>Edit Profile</title>

{% endblock %}

	{% block body %}
	<div class="container">
	
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit">Submit</button>
			}
		</form>

	</div>
	
	{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<title>Login</title>
<h1>Log-in to POST!</h1>
<p>
	
</p>

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Login</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<title>Logout</title>
<h1>Logged OFF!!</h1>
<p>
	Come back to post content.
</p>

</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


	{% block head%}
	<title>Profile</title>
	{% endblock %}


	{% block body %}
	<div class="container">
	
	<h1>{{ user }}</h1>
	<p>{{ user.email }}	</p>
	<p>Bio: {{user.userprofile.bio}}</p>
	<p>Website: {{user.userprofile.website}}</p>
	<img src="{{ user.userprofile.image.url }}" width = "240">

	</div>
	
	{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<h1>Register to POST!</h1>

	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<button type = "submit">Submit</button>
	</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<title>Reset Password</title>
<h1>Password Reset</h1>
<p>
	Have you disgracefully forgot you password? Enter your e-mail and we will help you make a new one.
</p>

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Reset Password</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<title>Complete</title>
<h1>Password reset complete</h1>

<a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">

<h1>Enter ne password</h1>
<p>
	
</p>

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Reset Password</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<title>Reset Password</title>
<h1>An email has been sent</h1>
<p>
	We've sent you an email giving instructions on how to reset you're password. 

	If you don't see one make sure you have entered the address you are registered with and check you spam folder.

	Don't dishonor yourself again.
</p>

</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" >Post Hole</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
    </body>
    <script 
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
      crossorigin="anonymous">
    </script>
    <script> window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
</html>